# Gradle settings
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
teaVmVersion=0.12.3

# NGE versions
ngePlatformVersion=0.2.0-SNAPSHOT
ngeVersion=0.2.0-SNAPSHOT

# Build targets
withDesktopPlatform=true
withAndroidPlatform=false
withWebPlatform=true
withIOSCapacitorPlatform=true

# Project settings
version=1.0.0
versionCode=1

appName=son
appFullName=Sea of Nostriches
appId=org.ngengine.demo.son

copyright=Copyright (c) 2025
javaOptions= 
