/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class TestNGEAppMain {
    @Test public void okTest() {
        assertTrue("This test should always pass", true);         
    }
}
